Cards flip two at a time. Breaks after that.
Cards are flipping properly, only two at a time. Working on the match function, but it breaks on line 40, and the error says:
TypeError: Cannot set property `className` of undefined